-- Generated by tools/ghost-frames.sh from the README ghost GIF: the band visible above the
-- text line, tinted to the editor foreground, empty lead-in frames dropped.
return {
  delay_ms = 20,
  frames = {
    "frame-01.png",
    "frame-02.png",
    "frame-03.png",
    "frame-04.png",
    "frame-05.png",
    "frame-06.png",
    "frame-07.png",
    "frame-08.png",
    "frame-09.png",
    "frame-10.png",
    "frame-11.png",
    "frame-12.png",
  },
}
