local p = require("spooky-scary.palette")

return {
  Normal = { fg = p.editorForeground, bg = p.editorBackground },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = p.editorForeground, bg = p.menuBackground },
  FloatBorder = { fg = p.focusBorder, bg = p.menuBackground },
  FloatTitle = { fg = p.sideBarSectionHeaderForeground, bg = p.menuBackground },
  EndOfBuffer = { fg = p.editorBackground },
  NonText = { fg = p.statusBarForeground },
  SpecialKey = { fg = p.statusBarForeground },
  Whitespace = { fg = p.activityBarBadgeBackground },
  Conceal = { fg = p.statusBarForeground },

  LineNr = { fg = p.statusBarForeground },
  LineNrAbove = { link = "LineNr" },
  LineNrBelow = { link = "LineNr" },
  CursorLineNr = { fg = p.lineNumberActiveForeground, bold = true },
  CursorLine = { bg = p.activityBarBadgeBackground },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = p.activityBarBadgeBackground },
  SignColumn = { fg = p.statusBarForeground, bg = p.editorBackground },
  FoldColumn = { fg = p.statusBarForeground, bg = p.editorBackground },
  Folded = { fg = p.textLinkForeground, bg = p.activityBarBadgeBackground },

  -- The theme sets both cursor colors to green, so a block cursor hides its character in VS Code too.
  Cursor = { fg = p.cursor, bg = p.cursor },
  lCursor = { link = "Cursor" },
  CursorIM = { link = "Cursor" },
  TermCursor = { link = "Cursor" },
  TermCursorNC = { fg = p.editorBackground, bg = p.statusBarForeground },

  Visual = { fg = p.selectionForeground, bg = p.selectionBackground },
  VisualNOS = { link = "Visual" },
  -- findMatchBackground is the current match; other matches keep VS Code's default dark highlight.
  Search = { bg = p.blend("#ea5c0055", p.editorBackground) },
  CurSearch = { fg = p.editorBackground, bg = p.findMatchBackground },
  IncSearch = { link = "CurSearch" },
  Substitute = { link = "CurSearch" },
  MatchParen = { fg = p.foreground, bold = true, underline = true },

  StatusLine = { fg = p.statusBarForeground, bg = p.statusBarBackground },
  StatusLineNC = { fg = p.statusBarForeground, bg = p.statusBarBackground },
  WinSeparator = { fg = p.editorGroupBorder },
  VertSplit = { link = "WinSeparator" },
  WinBar = { fg = p.breadcrumbForeground, bg = p.editorBackground },
  WinBarNC = { link = "WinBar" },

  TabLine = { fg = p.statusBarForeground, bg = p.tabInactiveBackground },
  TabLineFill = { bg = p.tabsBackground },
  TabLineSel = { fg = p.tabActiveForeground, bg = p.tabActiveBackground },

  Pmenu = { fg = p.foreground, bg = p.menuBackground },
  PmenuSel = { fg = p.menuBackground, bg = p.menuSelectionBackground },
  PmenuKind = { fg = p.textLinkForeground, bg = p.menuBackground },
  PmenuKindSel = { link = "PmenuSel" },
  PmenuExtra = { fg = p.statusBarForeground, bg = p.menuBackground },
  PmenuExtraSel = { link = "PmenuSel" },
  PmenuSbar = { bg = p.menuBackground },
  PmenuThumb = { bg = p.scrollbarSliderBackground },
  WildMenu = { link = "PmenuSel" },

  Directory = { fg = p.textLinkForeground },
  Title = { fg = p.markdownHeading, bold = true },
  Question = { fg = p.foreground },
  MoreMsg = { fg = p.foreground },
  ModeMsg = { fg = p.foreground, bold = true },
  MsgArea = { link = "Normal" },
  MsgSeparator = { link = "StatusLine" },
  ErrorMsg = { fg = p.invalid },
  WarningMsg = { fg = p.number },
  QuickFixLine = { bg = p.selectionBackground },

  -- The markup inserted, changed and deleted colors at 20 percent over the editor background.
  DiffAdd = { bg = p.blend("#C3E88D33", p.editorBackground) },
  DiffChange = { bg = p.blend("#C792EA33", p.editorBackground) },
  DiffDelete = { fg = p.deleted, bg = p.blend("#FF537033", p.editorBackground) },
  DiffText = { bg = p.blend("#C792EA66", p.editorBackground) },
  Added = { fg = p.inserted },
  Changed = { fg = p.changed },
  Removed = { fg = p.deleted },

  SpellBad = { sp = p.invalid, undercurl = true },
  SpellCap = { sp = p.number, undercurl = true },
  SpellLocal = { sp = p.regexp, undercurl = true },
  SpellRare = { sp = p.attribute, undercurl = true },

  DiagnosticError = { fg = p.editorErrorForeground },
  DiagnosticWarn = { fg = p.number },
  DiagnosticInfo = { fg = p.textLinkForeground },
  DiagnosticHint = { fg = p.keyword },
  DiagnosticOk = { fg = p.foreground },
  DiagnosticUnderlineError = { sp = p.editorErrorForeground, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.number, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.textLinkForeground, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.keyword, undercurl = true },
  DiagnosticUnderlineOk = { sp = p.foreground, undercurl = true },
  DiagnosticVirtualTextError = { fg = p.editorErrorForeground, bg = p.activityBarBadgeBackground },
  DiagnosticVirtualTextWarn = { fg = p.number, bg = p.activityBarBadgeBackground },
  DiagnosticVirtualTextInfo = { fg = p.textLinkForeground, bg = p.activityBarBadgeBackground },
  DiagnosticVirtualTextHint = { fg = p.keyword, bg = p.activityBarBadgeBackground },
  DiagnosticVirtualTextOk = { fg = p.foreground, bg = p.activityBarBadgeBackground },
  DiagnosticSignError = { link = "DiagnosticError" },
  DiagnosticSignWarn = { link = "DiagnosticWarn" },
  DiagnosticSignInfo = { link = "DiagnosticInfo" },
  DiagnosticSignHint = { link = "DiagnosticHint" },
  DiagnosticSignOk = { link = "DiagnosticOk" },
  DiagnosticDeprecated = { strikethrough = true },
  DiagnosticUnnecessary = { fg = p.statusBarForeground },

  LspReferenceText = { bg = p.activityBarBadgeBackground },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspInlayHint = { fg = p.statusBarForeground, bg = p.activityBarBadgeBackground },
  LspSignatureActiveParameter = { fg = p.number, bold = true },
  LspCodeLens = { fg = p.statusBarForeground },
}
