local p = require("spooky-scary.palette")

return {
	-- bufferline: tabs from the VS Code tab colors.
	BufferLineFill = { bg = p.tabsBackground },
	BufferLineBackground = { fg = p.statusBarForeground, bg = p.tabInactiveBackground },
	BufferLineBuffer = { fg = p.statusBarForeground, bg = p.tabInactiveBackground },
	BufferLineBufferVisible = { fg = p.statusBarForeground, bg = p.tabActiveBackground },
	BufferLineBufferSelected = { fg = p.tabActiveForeground, bg = p.tabActiveBackground, bold = true },
	BufferLineSeparator = { fg = p.tabsBackground, bg = p.tabInactiveBackground },
	BufferLineSeparatorVisible = { fg = p.tabsBackground, bg = p.tabActiveBackground },
	BufferLineSeparatorSelected = { fg = p.tabsBackground, bg = p.tabActiveBackground },
	BufferLineIndicatorSelected = { fg = p.focusBorder, bg = p.tabActiveBackground },
	BufferLineIndicatorVisible = { fg = p.tabActiveBackground, bg = p.tabActiveBackground },
	BufferLineModified = { fg = p.foreground, bg = p.tabInactiveBackground },
	BufferLineModifiedVisible = { fg = p.foreground, bg = p.tabActiveBackground },
	BufferLineModifiedSelected = { fg = p.foreground, bg = p.tabActiveBackground },
	BufferLineCloseButton = { fg = p.statusBarForeground, bg = p.tabInactiveBackground },
	BufferLineCloseButtonVisible = { fg = p.statusBarForeground, bg = p.tabActiveBackground },
	BufferLineCloseButtonSelected = { fg = p.tabActiveForeground, bg = p.tabActiveBackground },
	BufferLineTab = { fg = p.statusBarForeground, bg = p.tabInactiveBackground },
	BufferLineTabSelected = { fg = p.tabActiveForeground, bg = p.tabActiveBackground },
	BufferLineTabSeparator = { fg = p.tabsBackground, bg = p.tabInactiveBackground },
	BufferLineTabSeparatorSelected = { fg = p.tabsBackground, bg = p.tabActiveBackground },
	BufferLineTabClose = { fg = p.statusBarForeground, bg = p.tabsBackground },
	BufferLineDuplicate = { fg = p.statusBarForeground, bg = p.tabInactiveBackground, italic = true },
	BufferLineDuplicateVisible = { fg = p.statusBarForeground, bg = p.tabActiveBackground, italic = true },
	BufferLineDuplicateSelected = { fg = p.tabActiveForeground, bg = p.tabActiveBackground, italic = true },
	BufferLineError = { fg = p.editorErrorForeground, bg = p.tabInactiveBackground },
	BufferLineErrorSelected = { fg = p.editorErrorForeground, bg = p.tabActiveBackground, bold = true },
	BufferLineWarning = { fg = p.number, bg = p.tabInactiveBackground },
	BufferLineWarningSelected = { fg = p.number, bg = p.tabActiveBackground, bold = true },

	-- nvim-tree: the VS Code side bar.
	NvimTreeNormal = { fg = p.foreground, bg = p.sideBarBackground },
	NvimTreeNormalNC = { link = "NvimTreeNormal" },
	NvimTreeNormalFloat = { link = "NvimTreeNormal" },
	NvimTreeEndOfBuffer = { fg = p.sideBarBackground, bg = p.sideBarBackground },
	NvimTreeWinSeparator = { fg = p.sideBarBackground, bg = p.sideBarBackground },
	NvimTreeCursorLine = { bg = p.activityBarBadgeBackground },
	NvimTreeRootFolder = { fg = p.sideBarSectionHeaderForeground, bold = true },
	NvimTreeFolderName = { fg = p.textLinkForeground },
	NvimTreeFolderIcon = { fg = p.focusBorder },
	NvimTreeOpenedFolderName = { fg = p.textLinkForeground, bold = true },
	NvimTreeEmptyFolderName = { fg = p.statusBarForeground },
	NvimTreeFileName = { fg = p.foreground },
	NvimTreeOpenedFile = { fg = p.foreground, bold = true },
	NvimTreeSpecialFile = { fg = p.number },
	NvimTreeExecFile = { fg = p.inserted },
	NvimTreeImageFile = { fg = p.attribute },
	NvimTreeSymlink = { fg = p.regexp },
	NvimTreeIndentMarker = { fg = p.activityBarBadgeBackground },
	NvimTreeGitDirty = { fg = p.changed },
	NvimTreeGitStaged = { fg = p.inserted },
	NvimTreeGitMerge = { fg = p.gitConflicting },
	NvimTreeGitRenamed = { fg = p.changed },
	NvimTreeGitNew = { fg = p.inserted },
	NvimTreeGitDeleted = { fg = p.deleted },
	NvimTreeGitIgnored = { fg = p.statusBarForeground },
	NvimTreeLspDiagnosticsError = { link = "DiagnosticError" },
	NvimTreeLspDiagnosticsWarning = { link = "DiagnosticWarn" },
	NvimTreeLspDiagnosticsInformation = { link = "DiagnosticInfo" },
	NvimTreeLspDiagnosticsHint = { link = "DiagnosticHint" },

	-- telescope: side bar background with focus border.
	TelescopeNormal = { fg = p.foreground, bg = p.sideBarBackground },
	TelescopeBorder = { fg = p.focusBorder, bg = p.sideBarBackground },
	TelescopeTitle = { fg = p.sideBarSectionHeaderForeground, bold = true },
	TelescopePromptNormal = { fg = p.foreground, bg = p.menuBackground },
	TelescopePromptBorder = { fg = p.focusBorder, bg = p.menuBackground },
	TelescopePromptTitle = { fg = p.menuBackground, bg = p.focusBorder, bold = true },
	TelescopePromptPrefix = { fg = p.foreground },
	TelescopePromptCounter = { fg = p.statusBarForeground },
	TelescopeResultsTitle = { link = "TelescopeTitle" },
	TelescopePreviewTitle = { link = "TelescopeTitle" },
	TelescopeSelection = { fg = p.menuBackground, bg = p.menuSelectionBackground },
	TelescopeSelectionCaret = { fg = p.foreground, bg = p.menuSelectionBackground },
	TelescopeMultiSelection = { fg = p.number, bg = p.sideBarBackground },
	TelescopeMatching = { fg = p.textLinkActiveForeground, bold = true },
	TelescopeResultsComment = { fg = p.statusBarForeground },

	-- gitsigns: the markup inserted, changed and deleted colors.
	GitSignsAdd = { fg = p.inserted },
	GitSignsChange = { fg = p.changed },
	GitSignsDelete = { fg = p.deleted },
	GitSignsTopdelete = { fg = p.deleted },
	GitSignsChangedelete = { fg = p.changed },
	GitSignsUntracked = { fg = p.inserted },
	GitSignsAddNr = { link = "GitSignsAdd" },
	GitSignsChangeNr = { link = "GitSignsChange" },
	GitSignsDeleteNr = { link = "GitSignsDelete" },
	GitSignsAddLn = { link = "DiffAdd" },
	GitSignsChangeLn = { link = "DiffChange" },
	GitSignsDeleteLn = { link = "DiffDelete" },
	GitSignsCurrentLineBlame = { fg = p.statusBarForeground, italic = true },
	GitSignsAddInline = { link = "DiffText" },
	GitSignsChangeInline = { link = "DiffText" },
	GitSignsDeleteInline = { link = "DiffText" },

	-- nvim-cmp: the VS Code menu, with kinds colored like the symbol icons.
	CmpItemAbbr = { fg = p.foreground },
	CmpItemAbbrDeprecated = { fg = p.statusBarForeground, strikethrough = true },
	CmpItemAbbrMatch = { fg = p.textLinkActiveForeground, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = p.textLinkActiveForeground },
	CmpItemMenu = { fg = p.statusBarForeground },
	CmpItemKind = { fg = p.focusBorder },
	CmpItemKindClass = { fg = p.focusBorder },
	CmpItemKindVariable = { fg = p.focusBorder },
	CmpItemKindField = { fg = p.focusBorder },
	CmpItemKindFunction = { fg = p.func },
	CmpItemKindMethod = { fg = p.func },
	CmpItemKindConstructor = { fg = p.classSupport },
	CmpItemKindInterface = { fg = p.classSupport },
	CmpItemKindStruct = { fg = p.classSupport },
	CmpItemKindEnum = { fg = p.classSupport },
	CmpItemKindEnumMember = { fg = p.number },
	CmpItemKindConstant = { fg = p.number },
	CmpItemKindValue = { fg = p.number },
	CmpItemKindUnit = { fg = p.number },
	CmpItemKindKeyword = { fg = p.keyword },
	CmpItemKindOperator = { fg = p.keyword },
	CmpItemKindModule = { fg = p.classSupport },
	CmpItemKindProperty = { fg = p.variable },
	CmpItemKindText = { fg = p.foreground },
	CmpItemKindSnippet = { fg = p.attribute },
	CmpItemKindFile = { fg = p.textLinkForeground },
	CmpItemKindFolder = { fg = p.textLinkForeground },
	CmpItemKindColor = { fg = p.colorConstant },
	CmpItemKindReference = { fg = p.regexp },
	CmpItemKindEvent = { fg = p.regexp },
	CmpItemKindTypeParameter = { fg = p.entityType },

	-- indent-blankline.
	IblIndent = { fg = p.activityBarBadgeBackground },
	IblWhitespace = { fg = p.activityBarBadgeBackground },
	IblScope = { fg = p.focusBorder },

	-- which-key: the VS Code menu.
	WhichKey = { fg = p.foreground },
	WhichKeyGroup = { fg = p.textLinkForeground },
	WhichKeyDesc = { fg = p.editorForeground },
	WhichKeySeparator = { fg = p.statusBarForeground },
	WhichKeyFloat = { bg = p.menuBackground },
	WhichKeyBorder = { fg = p.focusBorder, bg = p.menuBackground },
	WhichKeyTitle = { fg = p.sideBarSectionHeaderForeground, bg = p.menuBackground },
	WhichKeyValue = { fg = p.statusBarForeground },

	-- render-markdown: heading text is gold like the theme's entity.name.section rule.
	RenderMarkdownH1 = { fg = p.classSupport },
	RenderMarkdownH2 = { fg = p.classSupport },
	RenderMarkdownH3 = { fg = p.classSupport },
	RenderMarkdownH4 = { fg = p.classSupport },
	RenderMarkdownH5 = { fg = p.classSupport },
	RenderMarkdownH6 = { fg = p.classSupport },
	RenderMarkdownH1Bg = { bg = p.blend("#C3E88D1a", p.editorBackground) },
	RenderMarkdownH2Bg = { bg = p.blend("#C3E88D14", p.editorBackground) },
	RenderMarkdownH3Bg = { bg = p.blend("#C3E88D0f", p.editorBackground) },
	RenderMarkdownH4Bg = { bg = p.blend("#C3E88D0a", p.editorBackground) },
	RenderMarkdownH5Bg = { bg = p.blend("#C3E88D05", p.editorBackground) },
	RenderMarkdownH6Bg = { bg = p.editorBackground },
	RenderMarkdownCode = { bg = p.menuBackground },
	RenderMarkdownCodeInline = { fg = p.markdownPlain, bg = p.menuBackground },
	RenderMarkdownBullet = { fg = p.operatorMisc },
	RenderMarkdownQuote = { fg = p.operatorMisc, italic = true },
	RenderMarkdownDash = { fg = p.markdownMuted, bold = true },
	RenderMarkdownLink = { fg = p.markdownLink },
	RenderMarkdownTableHead = { fg = p.markdownPlain },
	RenderMarkdownTableRow = { fg = p.markdownPlain },
	RenderMarkdownChecked = { fg = p.markdownLink },
	RenderMarkdownUnchecked = { fg = p.markdownPlain },

	-- todo-comments.
	TodoBgTODO = { fg = p.editorBackground, bg = p.foreground, bold = true },
	TodoFgTODO = { fg = p.foreground },
	TodoSignTODO = { fg = p.foreground },
	TodoBgFIX = { fg = p.editorBackground, bg = p.invalid, bold = true },
	TodoFgFIX = { fg = p.invalid },
	TodoSignFIX = { fg = p.invalid },
	TodoBgHACK = { fg = p.editorBackground, bg = p.number, bold = true },
	TodoFgHACK = { fg = p.number },
	TodoSignHACK = { fg = p.number },
	TodoBgWARN = { fg = p.editorBackground, bg = p.number, bold = true },
	TodoFgWARN = { fg = p.number },
	TodoSignWARN = { fg = p.number },
	TodoBgPERF = { fg = p.editorBackground, bg = p.attribute, bold = true },
	TodoFgPERF = { fg = p.attribute },
	TodoSignPERF = { fg = p.attribute },
	TodoBgNOTE = { fg = p.editorBackground, bg = p.textLinkForeground, bold = true },
	TodoFgNOTE = { fg = p.textLinkForeground },
	TodoSignNOTE = { fg = p.textLinkForeground },
	TodoBgTEST = { fg = p.editorBackground, bg = p.regexp, bold = true },
	TodoFgTEST = { fg = p.regexp },
	TodoSignTEST = { fg = p.regexp },

	-- -- alpha-nvim dashboard: the logo in the theme's lime green, buttons in link purple.
	-- AlphaHeader = { fg = p.foreground },
	-- AlphaButtons = { fg = p.textLinkForeground },
	-- AlphaShortcut = { fg = p.number },
	-- AlphaFooter = { fg = p.statusBarForeground, italic = true },

	-- Lazy and mason floats reuse the menu.
	LazyNormal = { link = "NormalFloat" },
	MasonNormal = { link = "NormalFloat" },
}
