local p = require("spooky-scary.palette")

local groups = {
  ["@comment"] = { link = "Comment" },
  ["@comment.documentation"] = { link = "Comment" },
  ["@comment.error"] = { fg = p.invalid, italic = true },
  ["@comment.warning"] = { fg = p.number, italic = true },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { fg = p.textLinkForeground, italic = true },

  ["@variable"] = { link = "Identifier" },
  ["@variable.builtin"] = { fg = p.languageVariable, italic = true },
  ["@variable.parameter"] = { fg = p.number },
  ["@variable.parameter.builtin"] = { fg = p.number },
  ["@variable.member"] = { link = "Identifier" },

  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Constant" },
  ["@constant.macro"] = { link = "Constant" },
  ["@module"] = { fg = p.classSupport },
  ["@module.builtin"] = { fg = p.classSupport },
  ["@label"] = { link = "Label" },

  ["@string"] = { link = "String" },
  ["@string.documentation"] = { link = "String" },
  ["@string.regexp"] = { fg = p.regexp },
  ["@string.escape"] = { fg = p.escape },
  ["@string.special"] = { link = "String" },
  ["@string.special.symbol"] = { link = "String" },
  ["@string.special.url"] = { fg = p.textLinkForeground, underline = true },
  ["@string.special.path"] = { link = "String" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@boolean"] = { link = "Boolean" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },

  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.entityType },
  ["@type.definition"] = { link = "Type" },
  ["@type.qualifier"] = { link = "Keyword" },
  ["@attribute"] = { fg = p.decorator, italic = true },
  ["@attribute.builtin"] = { fg = p.decorator, italic = true },
  ["@property"] = { link = "Identifier" },

  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@function.call"] = { link = "Function" },
  ["@function.macro"] = { link = "Function" },
  ["@function.method"] = { link = "Function" },
  ["@function.method.call"] = { link = "Function" },
  ["@constructor"] = { fg = p.classSupport },
  ["@operator"] = { link = "Operator" },

  ["@keyword"] = { link = "Keyword" },
  ["@keyword.coroutine"] = { link = "Keyword" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.operator"] = { link = "Keyword" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.type"] = { link = "Keyword" },
  ["@keyword.modifier"] = { link = "Keyword" },
  ["@keyword.repeat"] = { link = "Repeat" },
  ["@keyword.return"] = { link = "Conditional" },
  ["@keyword.debugger"] = { link = "Conditional" },
  ["@keyword.exception"] = { link = "Exception" },
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.conditional.ternary"] = { link = "Operator" },
  ["@keyword.directive"] = { link = "PreProc" },
  ["@keyword.directive.define"] = { link = "Define" },

  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { link = "Delimiter" },
  ["@punctuation.special"] = { link = "Delimiter" },

  ["@markup.strong"] = { fg = p.markupBold, bold = true },
  ["@markup.italic"] = { fg = p.markupItalic, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { fg = p.markupUnderline, underline = true },
  ["@markup.heading"] = { fg = p.markdownHeading },
  ["@markup.heading.1"] = { link = "@markup.heading" },
  ["@markup.heading.2"] = { link = "@markup.heading" },
  ["@markup.heading.3"] = { link = "@markup.heading" },
  ["@markup.heading.4"] = { link = "@markup.heading" },
  ["@markup.heading.5"] = { link = "@markup.heading" },
  ["@markup.heading.6"] = { link = "@markup.heading" },
  ["@markup.quote"] = { italic = true },
  ["@markup.math"] = { fg = p.markdownPlain },
  ["@markup.link"] = { fg = p.markdownLinkAnchor },
  ["@markup.link.label"] = { fg = p.markdownLink },
  ["@markup.link.url"] = { fg = p.markdownPlain, underline = true },
  ["@markup.raw"] = { fg = p.markdownRawInline },
  ["@markup.raw.block"] = { fg = p.markdownPlain },
  ["@markup.list"] = { fg = p.markdownPlain },
  ["@markup.list.checked"] = { fg = p.inserted },
  ["@markup.list.unchecked"] = { fg = p.markdownPlain },

  ["@diff.plus"] = { fg = p.inserted },
  ["@diff.minus"] = { fg = p.deleted },
  ["@diff.delta"] = { fg = p.changed },

  ["@tag"] = { link = "Tag" },
  ["@tag.builtin"] = { link = "Tag" },
  ["@tag.attribute"] = { fg = p.attribute },
  ["@tag.delimiter"] = { fg = p.operatorMisc },

  -- JavaScript family. The grammar has no screaming-case rule, object keys and
  -- support properties match no rule, and `constructor` is a storage keyword.
  ["@constant.javascript"] = { link = "Identifier" },
  ["@constant.typescript"] = { link = "Identifier" },
  ["@constant.tsx"] = { link = "Identifier" },
  ["@property.javascript"] = { fg = p.editorForeground },
  ["@property.typescript"] = { fg = p.editorForeground },
  ["@property.tsx"] = { fg = p.editorForeground },

  -- HTML: attributes are italic orange only inside text.html.basic, and text inside
  -- elements has no rule, so headings, links and emphasis stay plain.
  ["@tag.attribute.html"] = { fg = p.htmlAttribute, italic = true },
  ["@operator.html"] = { fg = p.operatorMisc },
  ["@string.special.url.html"] = { fg = p.string },
  ["@character.special.html"] = { fg = p.number },
  ["@constant.html"] = { fg = p.tag },
  ["@markup.heading.html"] = { fg = p.editorForeground },
  ["@markup.strong.html"] = { fg = p.editorForeground },
  ["@markup.italic.html"] = { fg = p.editorForeground },
  ["@markup.underline.html"] = { fg = p.editorForeground },
  ["@markup.strikethrough.html"] = { fg = p.editorForeground },
  ["@markup.raw.html"] = { fg = p.editorForeground },
  ["@markup.link.html"] = { fg = p.editorForeground },
  ["@markup.link.label.html"] = { fg = p.editorForeground },
  ["@markup.link.url.html"] = { fg = p.editorForeground },

  -- CSS: property names, class selectors, ids and !important.
  ["@property.css"] = { fg = p.cssProperty },
  ["@type.css"] = { fg = p.cssClass },
  ["@constant.css"] = { fg = p.attribute },
  ["@keyword.modifier.css"] = { fg = p.number },
  ["@string.css"] = { fg = p.string },
  ["@tag.css"] = { fg = p.tag },
  ["@attribute.css"] = { fg = p.attribute },

  -- JSON: level 0 keys, and the quote marks the query marks for concealing are punctuation.
  ["@property.json"] = { fg = p.jsonKey0 },
  ["@conceal.json"] = { fg = p.operatorMisc },

  -- Python: the grammar leaves plain identifiers, imports and most types unscoped,
  -- and colors most non-flow keywords as control keywords.
  ["@variable.python"] = { fg = p.editorForeground },
  ["@variable.member.python"] = { fg = p.editorForeground },
  ["@constant.python"] = { fg = p.editorForeground },
  ["@module.python"] = { fg = p.editorForeground },
  ["@type.python"] = { fg = p.editorForeground },
  ["@keyword.python"] = { link = "Conditional" },
  ["@constructor.python"] = { link = "Function" },
  ["@attribute.python"] = { fg = p.entityType },
  ["@attribute.builtin.python"] = { fg = p.entityType },
  ["@punctuation.special.python"] = { fg = p.string },

  -- Lua: the grammar scopes no punctuation, so brackets and separators stay plain.
  ["@punctuation.delimiter.lua"] = { fg = p.editorForeground },
  ["@punctuation.bracket.lua"] = { fg = p.editorForeground },
  ["@constructor.lua"] = { fg = p.editorForeground },
  ["@constant.lua"] = { link = "Identifier" },
  ["@keyword.function.lua"] = { link = "Conditional" },
  ["@module.builtin.lua"] = { link = "Function" },
  ["@label.lua"] = { fg = p.number },

  -- Markdown: heading text is an entity name, paragraph text is near-white, and the
  -- emphasis, code span and link delimiters the query conceals are punctuation.
  ["@markup.heading.markdown"] = { fg = p.markdownPlain },
  ["@markup.heading.1.markdown"] = { fg = p.classSupport },
  ["@markup.heading.2.markdown"] = { fg = p.classSupport },
  ["@markup.heading.3.markdown"] = { fg = p.classSupport },
  ["@markup.heading.4.markdown"] = { fg = p.classSupport },
  ["@markup.heading.5.markdown"] = { fg = p.classSupport },
  ["@markup.heading.6.markdown"] = { fg = p.classSupport },
  ["@punctuation.special.markdown"] = { fg = p.operatorMisc },
  ["@punctuation.delimiter.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.checked.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.unchecked.markdown"] = { fg = p.operatorMisc },
  ["@markup.raw.block.markdown"] = { fg = p.markdownRawInline },
  ["@label.markdown"] = { fg = p.markdownPlain },
  ["@markup.quote.markdown"] = { fg = p.markdownPlain, italic = true },
  ["@markup.link.label.markdown"] = { fg = p.markdownLinkAnchor },
  ["@markup.link.url.markdown"] = { fg = p.markupUnderline, underline = true },
  ["@conceal.markdown_inline"] = { fg = p.operatorMisc },
  ["@markup.link.markdown_inline"] = { fg = p.operatorMisc },
  ["@markup.link.label.markdown_inline"] = { fg = p.markdownLink },
  ["@markup.link.url.markdown_inline"] = { fg = p.markupUnderline, underline = true },
  ["@markup.raw.markdown_inline"] = { fg = p.markdownPlain },
  ["@markup.strikethrough.markdown_inline"] = { fg = p.markdownPlain, strikethrough = true },
  ["@string.escape.markdown_inline"] = { fg = p.escape },
}

-- Clear LSP semantic token groups so treesitter colors win, as in VS Code with this theme.
for _, name in ipairs({
  "@lsp.type.class", "@lsp.type.comment", "@lsp.type.decorator", "@lsp.type.enum",
  "@lsp.type.enumMember", "@lsp.type.event", "@lsp.type.function", "@lsp.type.interface",
  "@lsp.type.keyword", "@lsp.type.macro", "@lsp.type.method", "@lsp.type.modifier",
  "@lsp.type.namespace", "@lsp.type.number", "@lsp.type.operator", "@lsp.type.parameter",
  "@lsp.type.property", "@lsp.type.regexp", "@lsp.type.string", "@lsp.type.struct",
  "@lsp.type.type", "@lsp.type.typeParameter", "@lsp.type.variable",
  "@lsp.mod.deprecated", "@lsp.mod.readonly", "@lsp.mod.defaultLibrary",
}) do
  groups[name] = {}
end

return groups
