local p = require("spooky-scary.palette")

local groups = {
  ["@comment"] = { link = "Comment" },
  ["@comment.documentation"] = { link = "Comment" },
  ["@comment.error"] = { fg = p.invalid, italic = true },
  ["@comment.warning"] = { fg = p.number, italic = true },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.note"] = { fg = p.textLinkForeground, italic = true },

  ["@variable"] = { link = "Identifier" },
  ["@variable.builtin"] = { fg = p.languageVariable, italic = true },
  ["@variable.parameter"] = { fg = p.number },
  ["@variable.parameter.builtin"] = { fg = p.number },
  ["@variable.member"] = { link = "Identifier" },

  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Constant" },
  ["@constant.macro"] = { link = "Constant" },
  ["@module"] = { fg = p.classSupport },
  ["@module.builtin"] = { fg = p.classSupport },
  ["@label"] = { link = "Label" },

  ["@string"] = { link = "String" },
  ["@string.documentation"] = { link = "String" },
  ["@string.regexp"] = { fg = p.regexp },
  ["@string.escape"] = { fg = p.escape },
  ["@string.special"] = { link = "String" },
  ["@string.special.symbol"] = { link = "String" },
  ["@string.special.url"] = { fg = p.textLinkForeground, underline = true },
  ["@string.special.path"] = { link = "String" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "Constant" },
  ["@boolean"] = { link = "Boolean" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },

  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.entityType },
  ["@type.definition"] = { link = "Type" },
  ["@type.qualifier"] = { link = "Keyword" },
  ["@attribute"] = { fg = p.decorator, italic = true },
  ["@attribute.builtin"] = { fg = p.decorator, italic = true },
  ["@property"] = { link = "Identifier" },

  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@function.call"] = { link = "Function" },
  ["@function.macro"] = { link = "Function" },
  ["@function.method"] = { link = "Function" },
  ["@function.method.call"] = { link = "Function" },
  ["@constructor"] = { fg = p.classSupport },
  ["@operator"] = { link = "Operator" },

  ["@keyword"] = { link = "Keyword" },
  ["@keyword.coroutine"] = { link = "Keyword" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.operator"] = { link = "Keyword" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.type"] = { link = "Keyword" },
  ["@keyword.modifier"] = { link = "Keyword" },
  ["@keyword.repeat"] = { link = "Repeat" },
  ["@keyword.return"] = { link = "Conditional" },
  ["@keyword.debugger"] = { link = "Conditional" },
  ["@keyword.exception"] = { link = "Exception" },
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.conditional.ternary"] = { link = "Operator" },
  ["@keyword.directive"] = { link = "PreProc" },
  ["@keyword.directive.define"] = { link = "Define" },

  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { link = "Delimiter" },
  ["@punctuation.special"] = { link = "Delimiter" },

  -- Private captures from this repo's queries/ extensions. Nothing else defines
  -- @spooky.*, so other colorschemes keep their base captures untouched.
  ["@spooky.plain"] = { fg = p.editorForeground },
  ["@spooky.punctuation"] = { link = "Delimiter" },
  ["@spooky.variable"] = { link = "Identifier" },
  ["@spooky.variable.block"] = { fg = p.blockVariable },
  ["@spooky.variable.language"] = { fg = p.languageVariable, italic = true },
  ["@spooky.parameter"] = { fg = p.number, nocombine = true },
  ["@spooky.function"] = { link = "Function" },
  ["@spooky.type"] = { link = "Type" },
  ["@spooky.type.builtin"] = { fg = p.entityType },
  ["@spooky.keyword"] = { link = "Keyword" },
  ["@spooky.keyword.other"] = { link = "Constant" },
  ["@spooky.comment"] = { link = "Comment" },
  ["@spooky.string"] = { link = "String" },
  ["@spooky.string.prefix"] = { link = "Keyword" },
  ["@spooky.string.escape"] = { fg = p.escape },
  ["@spooky.tag"] = { link = "Tag" },
  ["@spooky.attribute.html"] = { fg = p.htmlAttribute, italic = true },
  ["@spooky.json.key1"] = { fg = p.jsonKey1 },
  ["@spooky.json.key2"] = { fg = p.jsonKey2 },
  ["@spooky.json.key3"] = { fg = p.jsonKey3 },
  ["@spooky.json.key4"] = { fg = p.jsonKey4 },
  ["@spooky.json.key5"] = { fg = p.jsonKey5 },
  ["@spooky.json.key6"] = { fg = p.jsonKey6 },
  ["@spooky.json.key7"] = { fg = p.jsonKey7 },
  ["@spooky.json.key8"] = { fg = p.jsonKey8 },
  ["@spooky.markup.plain"] = { fg = p.markdownPlain },
  ["@spooky.markup.heading.marker"] = { fg = p.markdownHeading },
  ["@spooky.markup.raw.block"] = { fg = p.markdownRawInline },
  ["@spooky.markup.separator"] = { fg = p.markdownMuted, bold = true },
  ["@spooky.markup.link.label"] = { fg = p.markdownLink },
  ["@spooky.markup.link.title"] = { fg = p.markdownLinkDescription },
  ["@spooky.markup.link.description"] = { fg = p.otherVariable },
  ["@spooky.markup.link.reference"] = { fg = p.markdownLinkAnchor },
  ["@spooky.markup.link.delimiter"] = { fg = p.operatorMisc, nocombine = true },
  ["@spooky.markup.link.url"] = { fg = p.markupUnderline, underline = true },
  ["@spooky.markup.strong"] = { fg = p.markupBold, bold = true, nocombine = true },
  ["@spooky.markup.delimiter.strong"] = { fg = p.operatorMisc, bold = true, nocombine = true },

  ["@markup.strong"] = { fg = p.markupBold, bold = true },
  ["@markup.italic"] = { fg = p.markupItalic, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { fg = p.markupUnderline, underline = true },
  ["@markup.heading"] = { fg = p.markdownHeading },
  ["@markup.heading.1"] = { link = "@markup.heading" },
  ["@markup.heading.2"] = { link = "@markup.heading" },
  ["@markup.heading.3"] = { link = "@markup.heading" },
  ["@markup.heading.4"] = { link = "@markup.heading" },
  ["@markup.heading.5"] = { link = "@markup.heading" },
  ["@markup.heading.6"] = { link = "@markup.heading" },
  ["@markup.quote"] = { italic = true },
  ["@markup.math"] = { fg = p.markdownPlain },
  ["@markup.link"] = { fg = p.markdownLinkAnchor },
  ["@markup.link.label"] = { fg = p.markdownLink },
  ["@markup.link.url"] = { fg = p.markdownPlain, underline = true },
  ["@markup.raw"] = { fg = p.markdownRawInline },
  ["@markup.raw.block"] = { fg = p.markdownPlain },
  ["@markup.list"] = { fg = p.markdownPlain },
  ["@markup.list.checked"] = { fg = p.inserted },
  ["@markup.list.unchecked"] = { fg = p.markdownPlain },

  ["@diff.plus"] = { fg = p.inserted },
  ["@diff.minus"] = { fg = p.deleted },
  ["@diff.delta"] = { fg = p.changed },

  ["@tag"] = { link = "Tag" },
  ["@tag.builtin"] = { link = "Tag" },
  ["@tag.attribute"] = { fg = p.attribute },
  ["@tag.delimiter"] = { fg = p.operatorMisc },

  -- JavaScript family. Screaming-case names, console and document are plain variables
  -- in TextMate; brackets other than braces have no rule; JSX text and template
  -- substitutions sit inside grey meta.tag or embedded scopes.
  ["@constant.javascript"] = { link = "Identifier" },
  ["@constant.typescript"] = { link = "Identifier" },
  ["@constant.tsx"] = { link = "Identifier" },
  ["@variable.builtin.javascript"] = { link = "Identifier" },
  ["@variable.builtin.typescript"] = { link = "Identifier" },
  ["@variable.builtin.tsx"] = { link = "Identifier" },
  ["@keyword.coroutine.javascript"] = { link = "Keyword" },
  ["@keyword.coroutine.typescript"] = { link = "Keyword" },
  ["@keyword.coroutine.tsx"] = { link = "Keyword" },
  ["@punctuation.bracket.javascript"] = {},
  ["@punctuation.bracket.typescript"] = {},
  ["@punctuation.bracket.tsx"] = {},
  ["@none.javascript"] = { link = "Delimiter" },
  ["@none.typescript"] = { link = "Delimiter" },
  ["@none.tsx"] = { link = "Delimiter" },
  ["@attribute.javascript"] = { link = "Identifier" },
  ["@attribute.typescript"] = { link = "Identifier" },
  ["@attribute.tsx"] = { link = "Identifier" },
  ["@keyword.directive.javascript"] = { link = "String" },

  -- HTML: attributes are italic orange only inside text.html.basic, and text inside
  -- elements has no rule, so headings, links and emphasis stay plain.
  ["@tag.attribute.html"] = { fg = p.htmlAttribute, italic = true },
  ["@operator.html"] = { fg = p.operatorMisc },
  ["@string.special.url.html"] = { fg = p.string },
  ["@constant.html"] = { fg = p.tag },
  ["@markup.heading.html"] = { fg = p.editorForeground },
  ["@markup.heading.1.html"] = { fg = p.editorForeground },
  ["@markup.heading.2.html"] = { fg = p.editorForeground },
  ["@markup.heading.3.html"] = { fg = p.editorForeground },
  ["@markup.heading.4.html"] = { fg = p.editorForeground },
  ["@markup.heading.5.html"] = { fg = p.editorForeground },
  ["@markup.heading.6.html"] = { fg = p.editorForeground },
  ["@markup.strong.html"] = { fg = p.editorForeground },
  ["@markup.italic.html"] = { fg = p.editorForeground },
  ["@markup.underline.html"] = { fg = p.editorForeground },
  ["@markup.strikethrough.html"] = { fg = p.editorForeground },
  ["@markup.raw.html"] = { fg = p.editorForeground },
  ["@markup.link.html"] = { fg = p.editorForeground },
  ["@markup.link.label.html"] = { fg = p.editorForeground },
  ["@markup.link.url.html"] = { fg = p.editorForeground },

  -- CSS: property names, class selectors, ids and !important.
  ["@property.css"] = { fg = p.cssProperty },
  ["@type.css"] = { fg = p.cssClass },
  ["@constant.css"] = { fg = p.attribute },
  ["@keyword.modifier.css"] = { fg = p.number },
  ["@string.css"] = { fg = p.string },
  ["@tag.css"] = { fg = p.tag },
  ["@attribute.css"] = { fg = p.attribute },

  -- JSON: level 0 keys. Deeper levels come from queries/json via @spooky.json.keyN.
  ["@property.json"] = { fg = p.jsonKey0 },

  -- Python: the grammar leaves plain identifiers, imports and most types unscoped. These
  -- groups are empty rather than colored so the lower-priority call-argument capture
  -- from queries/python can show through.
  ["@variable.python"] = {},
  ["@variable.member.python"] = {},
  ["@constant.python"] = {},
  ["@module.python"] = { fg = p.editorForeground },
  ["@type.python"] = {},
  ["@type.definition.python"] = { link = "Type" },
  ["@keyword.python"] = { link = "Conditional" },
  ["@keyword.coroutine.python"] = { link = "Conditional" },
  ["@constructor.python"] = { link = "Function" },
  ["@attribute.python"] = { link = "Function" },
  ["@attribute.builtin.python"] = { fg = p.entityType },
  ["@punctuation.special.python"] = { fg = p.string },
  -- @none resets f-string interpolations, whose unscoped names take the editor foreground.
  ["@none.python"] = { fg = p.editorForeground },

  -- Lua: the grammar scopes no punctuation, so brackets and separators stay plain.
  ["@punctuation.delimiter.lua"] = { fg = p.editorForeground },
  ["@punctuation.bracket.lua"] = { fg = p.editorForeground },
  ["@constructor.lua"] = { fg = p.editorForeground },
  ["@variable.member.lua"] = { fg = p.editorForeground },
  ["@constant.lua"] = { link = "Identifier" },
  ["@keyword.function.lua"] = { link = "Conditional" },
  ["@keyword.directive.lua"] = { link = "Comment" },
  ["@module.builtin.lua"] = { link = "Function" },
  ["@label.lua"] = { fg = p.number },

  -- Markdown: heading text is an entity name, paragraph text is near-white, and the
  -- emphasis, code span and link delimiters the query conceals are punctuation.
  ["@markup.heading.markdown"] = { fg = p.markdownPlain },
  ["@markup.heading.1.markdown"] = { fg = p.classSupport },
  ["@markup.heading.2.markdown"] = { fg = p.classSupport },
  ["@markup.heading.3.markdown"] = { fg = p.classSupport },
  ["@markup.heading.4.markdown"] = { fg = p.classSupport },
  ["@markup.heading.5.markdown"] = { fg = p.classSupport },
  ["@markup.heading.6.markdown"] = { fg = p.classSupport },
  ["@punctuation.special.markdown"] = { fg = p.operatorMisc },
  ["@punctuation.delimiter.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.checked.markdown"] = { fg = p.operatorMisc },
  ["@markup.list.unchecked.markdown"] = { fg = p.operatorMisc },
  ["@markup.raw.block.markdown"] = { fg = p.markdownPlain },
  ["@label.markdown"] = { fg = p.markdownPlain },
  ["@markup.quote.markdown"] = { fg = p.markdownPlain, italic = true },
  ["@markup.link.label.markdown"] = { fg = p.markdownLinkAnchor },
  ["@markup.link.url.markdown"] = { fg = p.markupUnderline, underline = true },
  ["@conceal.markdown_inline"] = { fg = p.operatorMisc },
  ["@markup.link.markdown_inline"] = { fg = p.operatorMisc },
  ["@markup.link.label.markdown_inline"] = { fg = p.markdownLink },
  ["@markup.link.url.markdown_inline"] = { fg = p.markupUnderline, underline = true },
  ["@markup.raw.markdown_inline"] = { fg = p.markdownPlain },
  ["@markup.strong.markdown_inline"] = { fg = p.markupBold, bold = true, nocombine = true },
  ["@markup.strikethrough.markdown_inline"] = { fg = p.markdownPlain },
  ["@string.escape.markdown_inline"] = { fg = p.escape },
}

-- Clear LSP semantic token groups so treesitter colors win, as in VS Code with this theme.
for _, name in ipairs({
  "@lsp.type.class", "@lsp.type.comment", "@lsp.type.decorator", "@lsp.type.enum",
  "@lsp.type.enumMember", "@lsp.type.event", "@lsp.type.function", "@lsp.type.interface",
  "@lsp.type.keyword", "@lsp.type.macro", "@lsp.type.method", "@lsp.type.modifier",
  "@lsp.type.namespace", "@lsp.type.number", "@lsp.type.operator", "@lsp.type.parameter",
  "@lsp.type.property", "@lsp.type.regexp", "@lsp.type.string", "@lsp.type.struct",
  "@lsp.type.type", "@lsp.type.typeParameter", "@lsp.type.variable",
  "@lsp.mod.deprecated", "@lsp.mod.readonly", "@lsp.mod.defaultLibrary",
}) do
  groups[name] = {}
end

return groups
