#!/usr/bin/env bash
# Regenerates assets/ghost from the README's ghost GIF. Needs ffmpeg and python3.
# Usage: tools/ghost-frames.sh [local-ghost.gif]
#
# Power Mode shows the GIF in a 70px box whose top sits 30px above the text line, and the
# text layer covers the rest, so only the top 43 percent of each frame is ever visible. Its
# default "mask" background mode fills the GIF with the color of the token under the cursor.
# This crops to the visible band, drops frames that are empty after the crop, and writes one
# tinted frame set per theme color so the module can pick the set matching the cursor token.
set -euo pipefail
cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"
gif="${1:-$tmp/ghost.gif}"
if [ ! -f "$gif" ]; then
  curl -sL -o "$gif" "https://media.giphy.com/media/WngnWxxekMn8DIqmwQ/giphy.gif"
fi
rm -rf assets/ghost
mkdir -p assets/ghost
ffmpeg -v error -y -i "$gif" -vf "format=rgba,crop=176:116:136:0,scale=-1:64:flags=lanczos" "$tmp/frame-%02d.png"
# Every distinct token foreground in lua/spooky-scary/palette.lua: the editor foreground plus
# the values below its "Token colors" marker. Workbench backgrounds are skipped.
colors=$( { grep -oE 'editorForeground = "#[0-9a-fA-F]{6}"' lua/spooky-scary/palette.lua;
            sed -n '/-- Token colors/,$p' lua/spooky-scary/palette.lua; } \
          | grep -oE '"#[0-9a-fA-F]{6}"' | tr -d '"' | tr 'A-F' 'a-f' | sort -u | tr '\n' ' ')
python3 - "$tmp" $colors <<'PY'
import os, struct, subprocess, sys, zlib
src, colors = sys.argv[1], sys.argv[2:]
def has_alpha(path):
    data = open(path, 'rb').read(); pos = 8; chunks = []
    while pos < len(data):
        ln, = struct.unpack('>I', data[pos:pos+4]); typ = data[pos+4:pos+8]; body = data[pos+8:pos+8+ln]; pos += 12 + ln
        if typ == b'IHDR': w, h = struct.unpack('>II', body[:8])
        elif typ == b'IDAT': chunks.append(body)
    raw = zlib.decompress(b''.join(chunks)); stride = w * 4
    return any(any(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)][3::4]) for y in range(h))
kept = [n for n in sorted(os.listdir(src)) if n.endswith('.png') and has_alpha(os.path.join(src, n))]
for color in colors:
    r, g, b = (int(color[i:i+2], 16) / 255 for i in (1, 3, 5))
    out = f'assets/ghost/{color[1:]}'
    os.makedirs(out, exist_ok=True)
    for index, name in enumerate(kept, 1):
        subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', os.path.join(src, name),
                        '-vf', f'colorchannelmixer=rr={r:.4f}:gg={g:.4f}:bb={b:.4f}',
                        f'{out}/frame-{index:02d}.png'], check=True)
with open('assets/ghost/frames.lua', 'w') as f:
    f.write('-- Generated by tools/ghost-frames.sh from the README ghost GIF: the band visible above the\n'
            '-- text line, empty lead-in frames dropped, one directory per theme color.\n'
            'return {\n  delay_ms = 35,\n  colors = {\n')
    for color in colors: f.write(f'    "{color}",\n')
    f.write('  },\n  frames = {\n')
    for index in range(1, len(kept) + 1): f.write(f'    "frame-{index:02d}.png",\n')
    f.write('  },\n}\n')
print(f'{len(kept)} frames x {len(colors)} colors')
PY
