#!/usr/bin/env bash
# Regenerates assets/ghost from the README's ghost GIF. Needs ffmpeg and python3.
# Usage: tools/ghost-frames.sh [local-ghost.gif]
#
# Power Mode shows the GIF in a 70px box whose top sits 30px above the text line, and the
# text layer covers the rest, so only the top 43 percent of each frame is ever visible. The
# ghost is also drawn in the editor foreground purple there. This crops to that visible band,
# tints white to #a361ff while keeping the dark eyes, drops frames that are empty after the
# crop, and records the 20ms frame delay measured from the README's preview recording.
set -euo pipefail
cd "$(dirname "$0")/.."
tmp="$(mktemp -d)"
gif="${1:-$tmp/ghost.gif}"
if [ ! -f "$gif" ]; then
  curl -sL -o "$gif" "https://media.giphy.com/media/WngnWxxekMn8DIqmwQ/giphy.gif"
fi
find assets/ghost -name '*.png' -delete
ffmpeg -v error -y -i "$gif" \
  -vf "format=rgba,crop=176:116:136:0,colorchannelmixer=rr=0.639:gg=0.380:bb=1.0,scale=-1:64:flags=lanczos" \
  "$tmp/frame-%02d.png"
python3 - "$tmp" <<'PY'
import os, struct, sys, zlib
src = sys.argv[1]
def has_alpha(path):
    data = open(path, 'rb').read(); pos = 8; chunks = []
    while pos < len(data):
        ln, = struct.unpack('>I', data[pos:pos+4]); typ = data[pos+4:pos+8]; body = data[pos+8:pos+8+ln]; pos += 12 + ln
        if typ == b'IHDR': w, h = struct.unpack('>II', body[:8])
        elif typ == b'IDAT': chunks.append(body)
    raw = zlib.decompress(b''.join(chunks)); stride = w * 4
    # Alpha bytes survive every PNG filter as nonzero when any pixel is opaque, except the
    # rare case of filtered rows cancelling out exactly, which does not occur in these frames.
    for y in range(h):
        row = raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)]
        if any(row[3::4]): return True
    return False
kept = []
for name in sorted(os.listdir(src)):
    if name.endswith('.png') and has_alpha(os.path.join(src, name)):
        kept.append(name)
for index, name in enumerate(kept, 1):
    os.replace(os.path.join(src, name), f'assets/ghost/frame-{index:02d}.png')
with open('assets/ghost/frames.lua', 'w') as f:
    f.write('-- Generated by tools/ghost-frames.sh from the README ghost GIF: the band visible above the\n-- text line, tinted to the editor foreground, empty lead-in frames dropped.\nreturn {\n  delay_ms = 20,\n  frames = {\n')
    for index in range(1, len(kept) + 1):
        f.write(f'    "frame-{index:02d}.png",\n')
    f.write('  },\n}\n')
print(f'{len(kept)} frames kept')
PY
